### ISSUE TITLE
Mapbox content in the map.js file

### ISSUE THREAD

**Issue by Ramona2020** [HeardLibrary/map-template#7]
Mapbox Classics is going away on January 31st, and any existing mapbox editor projects will become read only.  Mapbox studio is replacing classic, but in order to keep the map-template viable for new adopters we need to update the code in map.js so that is works with Mapbox GL JS:  [https://www.mapbox.com/mapbox-gl-js/api/](url)  @Pema-sDaddy and I tried to solve this problem.  We created a working branch, mapbox-resolution, and started to revise the code.  We got as far as line 18, but it all went to downhill after that.  Todd and I are having a tough time figuring out how to update the rest of the code because we don't know how to distinguish all the bits of code that are specific to mapbox.  We need help from one who is wise in the ways of javascript. 😕

**Comment by CliffordAnderson** [comment]
@Ramona2020 @Pema-sDaddy I've created a branch to solve this problem. The basic functionality is now working on the new Mapbox-gl.js code. However, there is still some styling work to be done and I need to think about how to remove a few dummy points. So I'm leaving this issue open for now. Feel free to switch to this branch to test it out. You'll need Python's SimpleHTTPServer or something similar to try it.

**Comment by CliffordAnderson** [comment]
@Ramona2020 @Pema-sDaddy I've continued to refactor the application. You can now set the configuration information in a separate `config.js` file so that users will not need to edit `map.js` directly. Everything works with the newest version of Mapbox apart from switching the basemaps. I suggest closing this issue and opening a separate issue to fix that problem.
